version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backendnest"
    target-branch: "develop"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/backendnest"
    target-branch: "develop"
    schedule:
      interval: "weekly"
