services:
  postgres:
    image: postgres:18.0
    restart: always
    shm_size: 128mb
    container_name: agroManager-postgres-dev
    ports:
      - "5432:5432"
    env_file:
      - ./backendnest/.env.development
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "local_agroManager",
          "-d",
          "local_agroManager",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  redis:
    image: redis:8.2.3-alpine
    restart: always
    container_name: redis_local_agroManager
    ports:
      - "6379:6379"
    env_file:
      - ./backendnest/.env.development
    volumes:
      - /redis-data/:/data

volumes: #aprender sobre isso
  postgres-data:
