on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  linting:
    name: linting

    if: github.actor != 'dependabot[bot]'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: "25.x"
          cache: "npm"
          cache-dependency-path: ./backendnest/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./backendnest

      - name: Run Eslint
        run: npm run lint

  prettier:
    name: prettier

    if: github.actior != 'dependabot[bot]'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: "25.x"
          cache: npm
          cache-dependency-path: ./backendnest/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./backendnest

      - name: Run Prettier
        run: npm run format
