# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Agromanager CI

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: local_pg
          POSTGRES_PASSWORD: local_password_pg
          POSTGRES_DB: local_pg
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U local_pg"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:8.2.3-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "25.x"
          cache: "npm"
          cache-dependency-path: ./backendnest/package-lock.json

      - name: Create .env
        working-directory: ./backendnest
        env:
          THE_SECRET: ${{ secrets.TEST_ENV }}
        run: echo "$THE_SECRET" > .env.development

      - name: Install dependencies
        working-directory: ./backendnest
        run: npm ci

      - name: Run migrations
        working-directory: ./backendnest
        run: npm run migrate:dev

      - name: Run lint
        working-directory: ./backendnest
        run: npm run lint

      - name: Run tests
        working-directory: ./backendnest
        run: npm run test
        env:
          NODE_ENV: test

