# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Agromanager CI

on:
  pull_request:
    branches: [ "main","develop" ]

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Create .env
      working-directory: ./backendnest
      env:
        THE_SECRET: ${{ secrets.TEST_ENV }}
      run: echo "$THE_SECRET" > .env.development

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
      
    - name: Start containers
      run: docker compose up -d --build --wait

    - name: Run migrations
      run: docker compose exec -T node npm run migrate:dev

    - name: Run tests inside container
      run: docker compose exec -T node npm test
      env:
        NODE_ENV: test

    - name: Down containers
      if: always()
      run: docker compose down -v
