# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Agromanager CI

on:
  pull_request:
    branches: [ "main","develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        cache-dependency-path: ./backendnest/package-lock.json
    - run: echo "${{ secrets.TEST_ENV }}" > .env.test
      working-directory: ./backendnest
    - run: npm ci
      working-directory: ./backendnest
    - run: npm test
      working-directory: ./backendnest
